### ISSUE TITLE
Error while running the code

### ISSUE THREAD

**Issue by Toplica001** [KeivanKaboutari/AI-Beamforming#2]
Hello, great work. When I run the code i get the following error which i can't pass by: 
In an assignment  A(I) = B, the number of elements in B and I must be the same.

Error in mainFunctionMultiBeamAtDeterminedDirections (line 408)
            BeamMaxCRP(Counter) = max(BeamMatCPR(:,:,Counter), [], 'omitnan');

**Comment by KeivanKaboutari** [comment]
Hi,

 

Please send your modified code so I can look at it. Because line 408 is a comment on my codes.

 

Best Wishes.

 

From: Toplica001 ***@***.***> 
Sent: Monday, December 25, 2023 11:20 AM
To: KeivanKaboutari/AI-Beamforming ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [KeivanKaboutari/AI-Beamforming] Error while running the code (Issue #2)

 

Hello, great work. When I run the code i get the following error which i can't pass by:
In an assignment A(I) = B, the number of elements in B and I must be the same.

Error in mainFunctionMultiBeamAtDeterminedDirections (line 408)
BeamMaxCRP(Counter) = max(BeamMatCPR(:,:,Counter), [], 'omitnan');

**Comment by Toplica001** [comment]
Your line 408 might not be the same as mine cause I made few small changes
related to paths

**Comment by Toplica001** [comment]
Reminder to check my code.

Best,
TJ

**Comment by KeivanKaboutari** [comment]
Hi,

 

                You did not send your code to me. Send it to me to check it.

 

Best,

KK.

**Comment by Toplica001** [comment]
Sending you the script

**Comment by KeivanKaboutari** [comment]
Hi. Please send me your codes attached to an email. I do not find your codes!

**Comment by Toplica001** [comment]
I did send it in the last reply as a attachment. I will send it again later
because im nit at home at the moment.

**Comment by KeivanKaboutari** [comment]
There was no attached file in the previous email. Ok. NP.

**Comment by Toplica001** [comment]
I'm sending you file directly on gmail. Git doesn't allow me to attach matlab files. When you get this check email.
